"""rewrite_track

Revision ID: 1c07a37e775f
Revises: 75033854ca97
Create Date: 2026-07-23 01:12:43.715936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c07a37e775f'
down_revision: Union[str, Sequence[str], None] = '75033854ca97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'tags',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False,
                postgresql_using='tags::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'tags',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='tags::text')
    # ### end Alembic commands ###
