"""optional tg_file_id

Revision ID: bdd9b3a2bcf2
Revises: f91fba6d0820
Create Date: 2026-08-07 20:32:29.830660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd9b3a2bcf2'
down_revision: Union[str, Sequence[str], None] = 'f91fba6d0820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'tg_file_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'tg_file_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
